### ISSUE TITLE
Is it the final version code？

### ISSUE THREAD

**Issue by Gary-code** [HITsz-TMG/ExplainableVisualEntailment#1]
Congratulations on the paper accepted by ACM MM 2022, it is definitely an impressive work that well advance the SOTA of visual natural language explanation. I am wondering whether it is the final version of the code.

**Comment by MyLittleChange** [comment]
Thank you for your attention! And yes this is the final version.

**Comment by Gary-code** [comment]
Could you provide the feature file of the image? ex: feat_train.pkl

**Comment by MyLittleChange** [comment]
> Could you provide the feature file of the image? ex: feat_train.pkl

Sorry, the feature file is too large to upload, you can refer to [https://github.com/pzzhang/VinVL/blob/main/DOWNLOAD.md](url) for some part of the feature.

**Comment by MyLittleChange** [comment]
> Could you provide the feature file of the image? ex: feat_train.pkl

Sorry, the feature file is too large to upload, you can refer to [VinVL feature Download](https://github.com/pzzhang/VinVL/blob/main/DOWNLOAD.md) for some part of the feature.

**Comment by Gary-code** [comment]
The QA part of the model is treated as a classification problem, how is it classified for the VQA-X dataset? Considering that the answer of VQA dataset is open end.

**Comment by MyLittleChange** [comment]
> The QA part of the model is treated as a classification problem, how is it classified for the VQA-X dataset? Considering that the answer of VQA dataset is open end.

We follow [e-ViL benchmark](https://github.com/maximek3/e-ViL) and create a list which contains the possible answers.
